### ISSUE TITLE
JOSS Review: Documentation -- Functionality documentation

### ISSUE THREAD

**Issue by CFGrote** [jonathanHuwP/CrystalGrowthTracker#23]
From the project README or doxygen output, it does not become immediately clear how
cgt is supposed to be used. Can I use the API in a py script or am I to launch the GUI? I get the feeling both should be possible. For the former use case, I would need a starting example (see #22). For the latter use case, some screenshots would be great to assist first time users. This would also allow me to asses the review item "Functionality - Functionality: Have the functional claims of the software been confirmed?"

**Comment by jonathanHuwP** [comment]
@CFGrote @JoannaLeng

I have added a pargraph at the start of the README file describing the intended use of the software as a self contained package, rather than a library to be used in user scripts.
